group = com.aquaticstudios
version = 1.1.1

javaVersion = 17

adventureVersion = 4.17.0
adventurePlatformVersion = 4.3.4

centerMessageVersion = 3.0.1
headRenderVersion = 2.0.0
snakeyamlVersion = 2.2
bstatsVersion = 3.1.0

spigotVersion = 1.20.4-R0.1-SNAPSHOT
bungeeVersion = 1.21-R0.3
velocityVersion = 3.4.0-SNAPSHOT
placeholderApiVersion = 2.11.7

org.gradle.jvmargs = -Xmx2g
org.gradle.parallel = true
org.gradle.caching = true
